services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111555pat@gmail
      POSTGRES_DB: orders
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: ike20743/new-image:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orders
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 111555pat@gmail
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus
    depends_on:
      - postgres
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 128MB

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  reverse-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    restart: always
    command: /bin/sh -c "sleep 5 && nginx -g 'daemon off;'"  # Delay for app readiness

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
