global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8087']  # This should match your app container's internal address and port
